import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer"
import CartProvider from "./components/Provider";
import ShoppingCartModal from "./components/ShoppingCartModal";
import { Suspense } from "react";
import Loading from "./components/Loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Navbar />
          <ShoppingCartModal />
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
